model:
  - source_path: "/home/antonio-liguori/Documents/Projects/StableAI/nn_trust_personal/benchmark_assets/models/yolov8"

datasets:
  - source_path: "/home/antonio-liguori/Documents/Projects/StableAI/nn_trust_personal/benchmark_assets/datasets/coco_val2017"
    dataset_type: "coco"
    batch_size: 1
    num_workers: 1

attacks:
 - id: zoo
   max_iters: 3
   targeted: true
 - id: autozoom
   max_iters: 3
   targeted: true
 - id: _uap
   max_iters: 3
   targeted: true
 - id: daguap
   max_iters: 3
   targeted: true
 - id: fuap
   max_iters: 3
   targeted: true
 - id: fgsmuap
   max_iters: 3
   targeted: true
 - id: boundary
   max_iters: 3
   targeted: true
 - id: sphereprojection
   max_iters: 3
   targeted: true
 - id: advyoloevasion
   max_iters: 3
   targeted: true
 - id: banditpriorevasion
   max_iters: 3
   targeted: true
 - id: contrastbaselineevasion
   max_iters: 3
   targeted: true
 - id: gaussianbaselineevasion
   max_iters: 3
   targeted: true
 - id: saltnpeppernoisebaseline
   max_iters: 3
   targeted: true
 - id: uniformbaselineevasion
   max_iters: 3
   targeted: true
 - id: binaryevasion
   max_iters: 3
   targeted: true
 - id: blackboxtransfer
   max_iters: 3
   targeted: true
 - id: dag
   max_iters: 3
   targeted: true
 - id: deepfool
   max_iters: 3
   targeted: true
 - id: duevasion
   max_iters: 3
   targeted: true
 - id: fom
   max_iters: 3
   targeted: true
 - id: ofuapevasion
   max_iters: 3
   targeted: true
 - id: gduapevasion
   max_iters: 3
   targeted: true
 - id: geodaevasion
   max_iters: 3
   targeted: true
 - id: hopskipjump
   max_iters: 3
   targeted: true
 - id: jsm
   max_iters: 3
   targeted: true
 - id: localsearchevasion
   max_iters: 3
   targeted: true
 - id: parsimonious
   max_iters: 3
   targeted: true
 - id: pgdkde
   max_iters: 3
   targeted: true
 - id: priorgd
   max_iters: 3
   targeted: true
 - id: signoptevasion
   max_iters: 3
   targeted: true
 - id: simbaevasion
   max_iters: 3
   targeted: true
 - id: simpleblackboxevasion
   max_iters: 3
   targeted: true


metrics:
  - id: map
  - id: ap
  - id: iou
  - id: iou_target
  - id: misdetection
  - id: ssim

options:
  load_results: false                 # loading any existing results.
  overwrite: true                     # overwriting the results if a benchmarking is performed
  max_saved_elements: 10
  num_workers: 1
  verbose: true
  save_perturbation: false
  use_ray: false
  gpu: true
  create_pdf: true
  output_path: "/home/antonio-liguori/Documents/Projects/StableAI/nn_trust_personal/benchmark_output"
  targeted: false
  subset: 10