models:
  - source_path: "/home/antonio-liguori/Documents/Projects/StableAI/nn_trust_personal/benchmark_assets/models/yolov8"

datasets:
  - source_path: "/home/antonio-liguori/Documents/Projects/StableAI/nn_trust_personal/benchmark_assets/datasets/coco_val2017"
    batch_size: 8
    num_workers: 1

attacks:
 - id: zoo
 - id: autozoom
 - id: _uap
 - id: daguap
 - id: fuap
 - id: fgsmuap
 - id: boundary
 - id: sphereprojection
# - id: advyoloevasion
 - id: banditpriorevasion
 - id: contrastbaselineevasion
 - id: gaussianbaselineevasion
 - id: saltnpeppernoisebaseline
 - id: uniformbaselineevasion
 - id: binaryevasion
 - id: blackboxtransfer
 - id: dag
   max_iters: 10
   epsilon: 150.0
   top_k: 5
   label_target: 0
 - id: deepfool
 - id: duevasion
 - id: fom
 - id: ofuapevasion
 - id: gduapevasion
 - id: geodaevasion
 - id: hopskipjump
 - id: jsm
 - id: localsearchevasion
 - id: parsimonious
 - id: pgdkde
 - id: priorgd
 - id: signoptevasion
 - id: simbaevasion
 - id: simpleblackboxevasion


metrics:
  - id: map
  - id: ap
  - id: iou
  - id: iou_target
  - id: misdetection
  - id: ssim

options:
  load_results: false                 # loading any existing results.
  overwrite: true                     # overwriting the results if a benchmarking is performed
  max_saved_elements: 10
  num_workers: 1
  verbose: true
  save_perturbation: false
  use_ray: false
  gpu: true
  create_pdf: true
  output_path: "/home/antonio-liguori/Documents/Projects/StableAI/nn_trust_personal/benchmark_output"
  targeted: false
  subset: 5