models:
  - source_path: "~/Desktop/StableAI/model_repository/resnet50"

datasets:
  - name: "imagenet"
    num_classes: 1000
    batch: 20
    type_dataset: 1
    num_workers: 2
    source_path: "~/Desktop/StableAI/dataset_repository/imagenette2/"
    transform_config:
      size: 256
      crop: 224
      transform_id: "imagenet_like_crop"
      mean: [ 0.5074, 0.5308, 0.5306 ]
      std: [ 0.2639, 0.2518, 0.2521 ]

metrics:
  - id: 'countsamples'
  - id: 'accuracy'
  - id: 'f1score'
  - id: 'misclassification'
  - id: 'precision'
  - id: 'robustness'
  - id: 'class_robustness'



attacks:
  - id: "contrastbaselineevasion"
  - id: "gaussianbaselineevasion"
  - id: "identitybaselineevasion"
  - id: "saltnpeppernoisebaseline"
  - id: "uniformbaselineevasion"
  - id: "duevasion"
  - id: "fom"

options:
  load_results: false                 # loading any existing results.
  overwrite: true                     # overwriting the results if a benchmarking is performed
  num_images_to_save: 10
  num_workers: 1
  verbose: true
  subset: 50
  save_perturbation: false
  ray: false
  gpu: true
  output_path: "./benchmark_out" # Path to the output folder
  output_format: "report" # report or test



