
models: [ 'mobilenetv4_conv_blur_medium.e500_r224_in1k',
          'mobilenetv4_conv_medium.e500_r224_in1k',
          'mobilenetv4_hybrid_medium.e500_r224_in1k',
          'resnet101.a1_in1k',
          'resnet101.a1h_in1k',
          'resnet101.a2_in1k',
          'resnet101.gluon_in1k',
          'resnet101.tv_in1k',
          'resnet101c.gluon_in1k',
          'resnet101d.gluon_in1k',
          'resnet152.a1_in1k',
          'resnet152.a1h_in1k',
          'resnet152.a2_in1k',
          'resnet152.gluon_in1k',
          'resnet152.tv_in1k',
          'resnet152c.gluon_in1k',
          'resnet152d.gluon_in1k',
          'resnet152s.gluon_in1k',
          'resnetv2_18.ra4_e3600_r224_in1k',
          'resnetv2_18d.ra4_e3600_r224_in1k',
          'resnetv2_34.ra4_e3600_r224_in1k',
          'resnetv2_34d.ra4_e3600_r224_in1k',
          'resnetv2_50.a1h_in1k',
          'resnetv2_50d_evos.ah_in1k',
          'resnetv2_50d_gn.ah_in1k',
          'resnetv2_50x1_bit.goog_distilled_in1k',
          'resnetv2_101.a1h_in1k' ]