# generated by fastapi-codegen:
#   filename:  docs/titann_api_v1.yaml
#   timestamp: 2025-08-01T08:44:27+00:00

from __future__ import annotations

from typing import List, Optional, Dict, Any

from pydantic import BaseModel, Field

from typing import Literal

from nn_trust.core import AttackType, Knowledge

class Datasets(BaseModel):
    names: Optional[List[str]] = None


class Models(BaseModel):
    models: Optional[List[Dict]] = None


class Metric(BaseModel):
    values: Optional[float] = Field(None, example=0.8)


class Progress(BaseModel):
    progress: Optional[float] = Field(None, example=0.82)
    is_over : bool = Field(None, example=False)


class JobConfig(BaseModel):
    dataset: str = Field(..., example='cifar')
    model: str = Field(..., example='resnet50')

class AttackConfig(BaseModel):
    attack_name: str
    model_name : str
    image: str
    p: float = 2.0
    epsilon: float = 50.0
    max_iters: int = 30

class Error(BaseModel):
    code: int
    message: str

class Result(BaseModel):
    metrics: Optional[List[Metric]] = None

class BenchmarkJob(BaseModel):
    id: str 
    progress : float
    current_attack : str | None
    computing_global : bool = Field(default=False)
    attack_progress : float | None
    dataset : str
    model : str
    all_attacks : List[str]

class AttackJob(BaseModel):
    id: str 
    progress : float
    is_over : bool = Field(default=False)

class ModelConfig(BaseModel):
    name: str
    type: Optional[str] = None
    pretrained: bool
    num_classes: int
    task: Literal["classification"] 

class ParametersProps(BaseModel):
    name: str
    label: str
    min: float
    max: float
    step: float
    default: float
    description: str

class AttackProps(BaseModel):
    id: str
    name: str
    description: str
    knowledge: Optional[str] = None
    task: Optional[str] = None
    parameters: Optional[List[ParametersProps]] = None

class MetricProps(BaseModel):
    name: str

class ExecutionConfig(BaseModel):
    dataset: str
    model: str
    attacks: Any
    metrics: Any

class ReportProps(BaseModel):
    info: ReportInfoProps
    metrics: ReportMetricsProps
    attacks: Dict[str, ReportAttacksProps]


class ReportMetricsProps(BaseModel):
    params: int
    accuracy: Optional[float] = None
    precision: Optional[float] = None
    f1score: Optional[float] = None
    confusion_matrix: Optional[List[List[int]]] = None
    robustness: Optional[float] = None
    wobbliness: Optional[float] = None


class ReportAttacksProps(BaseModel):
    name: str
    risk: float
    accuracy: Optional[float] = None
    precision: Optional[float] = None
    f1score: Optional[float] = None
    misclassification: Optional[float] = None
    power: Optional[float] = None
    num_queries: Optional[int] = None
    robustness: Optional[List[float]] = None
    confusion_matrix: Optional[List[List[int]]] = None

class ReportInfoProps(BaseModel):
    id: str
    name: str
    parameters: int
    classes: int
    dimensionality: List[int]

