# generated by fastapi-codegen:
#   filename:  docs/titann_api_v1.yaml
#   timestamp: 2025-08-01T08:44:27+00:00

from __future__ import annotations

from typing import List, Optional, Dict

from pydantic import BaseModel, Field


class Datasets(BaseModel):
    names: Optional[List[str]] = None


class Models(BaseModel):
    models: Optional[List[Dict]] = None


class Metric(BaseModel):
    values: Optional[float] = Field(None, example=0.8)


class Progress(BaseModel):
    progress: Optional[float] = Field(None, example=0.82)
    is_over : bool = Field(None, example=False)


class JobConfig(BaseModel):
    dataset: str = Field(..., example='cifar')
    model: str = Field(..., example='resnet50')

class AttackConfig(BaseModel):
    attack_name: str
    image: str
    p: float = 2.0
    epsilon: float = 50.0
    max_iters: int = 30

class Error(BaseModel):
    code: int
    message: str

class Result(BaseModel):
    metrics: Optional[List[Metric]] = None

class BenchmarkJob(BaseModel):
    id: str 
    progress : float
    current_attack : str | None
    computing_global : bool = Field(default=False)
    attack_progress : float | None
    dataset : str
    model : str
    all_attacks : List[str]

class AttackJob(BaseModel):
    id: str 
    progress : float
    is_over : bool = Field(default=False)
