# generated by fastapi-codegen:
#   filename:  docs/titann_api_v1.yaml
#   timestamp: 2025-08-01T08:44:27+00:00

from __future__ import annotations

from typing import List, Optional, Dict, Any
from typing import Literal

from nn_trust.core import AttackType, Knowledge
from pydantic import BaseModel, Field, ConfigDict


####################### Basic configuration #######################
class Info(BaseModel):
    id: str  # id for the file identification.
    name: str  # File's name, ex. "Resnet50" or "Imagenette".
    image: Optional[str] = None  # an image that represents the file.
    task: str  # task associated with, i.e. classification, detection, etc.
    domain: str  # Domain where the input belongs
    classes: Optional[int] = None  # number of classes in the output.
    weights: Optional[float] = None  # Size of the file.
    input_dimensionality: List[int]  # dimensionality of each input or domain's dimensionality.
    description: Optional[str] = None  # description of the file.

    model_config = ConfigDict(extra='allow')


# Dataset's information
class DatasetInfo(Info):
    num_sample: int  # Number of samples, i.e. length of the dataset


# Model's information
class ModelInfo(Info):
    dataset: Optional[str] = None  # Dataset where the model had been optimized on
    parameters: Optional[int] = None  # Number of the models' parameters
    api: Optional[str] = None


###################################################################

class Error(BaseModel):
    code: int
    message: str


class Metric(BaseModel):
    values: Optional[float] = Field(None, example=0.8)


class BenchmarkJob(BaseModel):
    id: str
    progress: float
    current_attack: str | None
    computing_global: bool = Field(default=False)
    attack_progress: float | None
    dataset: str
    model: str
    all_attacks: List[str]


class ModelConfig(BaseModel):
    name: str
    type: Optional[str] = None
    pretrained: bool
    num_classes: int
    task: Literal["classification"]


########################### Register Object ###########################
class ParametersProps(BaseModel):
    id: str
    name: str
    min: float
    max: float
    step: float
    default: float
    description: str


class RegisteredObject(BaseModel):
    id: str
    name: str
    description: Optional[str] = None
    parameters: list[ParametersProps]
    task: str
    knowledge: Optional[str] = None


###################### Single Attack ######################
class SingleAttackProps(BaseModel):
    image: str
    id_model: str
    attack: RegisteredObject


class SingleAttackOutput(BaseModel):
    x: str
    x_adv: str
    adv_perturbation: str
    original_prediction: str
    adversarial_prediction: str
    confidence: dict[str, list[float]]
    advance_metrics: dict[str, float]


#######################################################################
class MetricProps(BaseModel):
    name: str


class ExecutionConfig(BaseModel):
    dataset: str
    model: str
    attacks: Any
    metrics: Any


class ReportProps(BaseModel):
    info: ReportInfoProps
    metrics: ReportMetricsProps
    attacks: Dict[str, ReportAttacksProps]


class ReportMetricsProps(BaseModel):
    params: int
    accuracy: Optional[float] = None
    precision: Optional[float] = None
    f1score: Optional[float] = None
    confusion_matrix: Optional[List[List[int]]] = None
    robustness: Optional[float] = None
    wobbliness: Optional[float] = None


class ReportAttacksProps(BaseModel):
    name: str
    risk: float
    accuracy: Optional[float] = None
    precision: Optional[float] = None
    f1score: Optional[float] = None
    misclassification: Optional[float] = None
    power: Optional[float] = None
    num_queries: Optional[int] = None
    robustness: Optional[List[float]] = None
    confusion_matrix: Optional[List[List[int]]] = None


class ReportInfoProps(BaseModel):
    id: str
    name: str
    parameters: int
    classes: int
    dimensionality: List[int]


class BenchmarkModelProps(BaseModel):
    name: str
    param: int
    task: str
    benchmark_id: str
    metrics: Dict[str, float | int]
