evaluation:
  statistics:
    - name: 'countsamples'
    - name: 'accuracy'
      average: 'macro'
    - name: 'precision'
      average: 'macro'
    - name: 'robustness'
    - name: 'misclassification'

options:
  load_results: false                 # loading any existing results.
  overwrite: true                     # overwriting the results if a benchmarking is performed
  num_images_to_save: -1
  save_perturbation: false
  gpu: true
  output_path: "./benchmark_out" # Path to the output folder
  output_format: "report" # report or test
  mode : "single_node_serial"
  num_workers : 1
  num_gpus_per_worker : 1
  executor_type : "ray"


datasets:
  - name: "imagenet" # Name of the dataset
    num_classes: 1000
    subset: 20
    batch: 5
    type_dataset: 1
    num_workers: 2
    source_path: "/home/bru/Documents/codes/data/imagenet-1k/val_images"
    transform_config:
      size: 256
      crop: 224
      transform_id: "imagenet_like_crop"
      mean: [0.5074, 0.5308, 0.5306]
      std: [0.2639, 0.2518, 0.2521]


models:

  - name: "timm/convnextv2_base.fcmae_ft_in1k"
    type: "huggingface"
    num_classes: 1000
    task: "classification"
    knowledge: "white"
    input_size: 224

  - name: "timm/vit_base_patch16_224.augreg2_in21k_ft_in1k"
    type: "huggingface"
    num_classes: 1000
    task: "classification"
    knowledge: "white"
    input_size: 224

  - model_path: "/home/bru/Documents/codes/nn_trust_apps/attack_server/models_repo/hf1_test"

attacks:
  - name: 'fgsm'
    max_iters: 20
  - name: 'banditprior'
    max_iters: 50
  - name: 'pgd'
    max_iters: 50


