# generated by fastapi-codegen:
#   filename:  titann_api_v1.yaml
#   timestamp: 2025-08-01T08:44:27+00:00

from __future__ import annotations
from typing import List, Optional, Union
from fastapi import FastAPI, UploadFile
from starlette.requests import Request
from .models import Datasets, Error, Job, JobConfig, Models, Progress, Result

app = FastAPI(
    title='Swagger TITANN backend',
    description='This is the TITANN backend.',
    termsOfService='https://swagger.io/terms/',
    contact={'email': 'apiteam@swagger.io'},
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    version='1.0.12',
    servers=[{'url': 'https://titann.swagger.io/api/v3'}],
)


@app.get(
    '/dataset/getDatasets',
    response_model=Datasets,
    responses={
        '400': {'model': Error},
        '404': {'model': Error},
        '500': {'model': Error},
    },
    tags=['datasets and models'],
)
def get_datasets() -> Union[Datasets, Error]:
    """
    Get all datasets of the TITANN backend.
    """
    pass


@app.post(
    '/dataset/upload',
    response_model=None,
    responses={
        '400': {'model': Error},
        '409': {'model': Error},
        '500': {'model': Error},
    },
    tags=['datasets and models'],
)
def upload_dataset(file: UploadFile) -> Optional[Error]:
    """
    Upload a dataset to the TITANN backend.
    """
    pass


@app.get(
    '/job/getJobsId',
    response_model=List[Job],
    responses={
        '400': {'model': Error},
        '404': {'model': Error},
        '500': {'model': Error},
    },
    tags=['jobs utils'],
)
def get_jobs_id() -> Union[List[Job], Error]:
    """
    Get all running jobs in the TITANN backend.
    """
    pass


@app.get(
    '/job/getProgress',
    response_model=Progress,
    responses={'400': {'model': Error}, '500': {'model': Error}},
    tags=['jobs management'],
)
def get_job_progress(id: str) -> Union[Progress, Error]:
    """
    Get a TITANN benchmark job progress.
    """
    pass


@app.get(
    '/job/getResult',
    response_model=Result,
    responses={
        '400': {'model': Error},
        '404': {'model': Error},
        '500': {'model': Error},
    },
    tags=['jobs management'],
)
def get_job_result(id: str) -> Union[Result, Error]:
    """
    Get a TITANN benchmark job result.
    """
    pass


@app.get(
    '/job/restart',
    response_model=None,
    responses={
        '400': {'model': Error},
        '409': {'model': Error},
        '500': {'model': Error},
    },
    tags=['jobs management'],
)
def restart_job(id: str) -> Optional[Error]:
    """
    Restart a new TITANN benchmark job from last checkpoint (last performed attack).
    """
    pass


@app.post(
    '/job/start',
    response_model=None,
    responses={'400': {'model': Error}, '500': {'model': Error}},
    tags=['jobs management'],
)
def start_job(body: JobConfig) -> Optional[Error]:
    """
    Start a new TITANN benchmark job.
    """
    pass


@app.get(
    '/job/stop',
    response_model=None,
    responses={
        '400': {'model': Error},
        '409': {'model': Error},
        '500': {'model': Error},
    },
    tags=['jobs management'],
)
def stop_job(id: str) -> Optional[Error]:
    """
    Stop a TITANN benchmark job.
    """
    pass


@app.get(
    '/model/getModels',
    response_model=Models,
    responses={
        '400': {'model': Error},
        '404': {'model': Error},
        '500': {'model': Error},
    },
    tags=['datasets and models'],
)
def get_models() -> Union[Models, Error]:
    """
    Get all models of the TITANN backend.
    """
    pass


@app.post(
    '/model/upload',
    response_model=None,
    responses={
        '400': {'model': Error},
        '409': {'model': Error},
        '500': {'model': Error},
    },
    tags=['datasets and models'],
)
def upload_model(file: UploadFile) -> Optional[Error]:
    """
    Upload a model to the TITANN backend.
    """
    pass
