# generated by fastapi-codegen:
#   filename:  docs/titann_api_v1.yaml
#   timestamp: 2025-08-01T08:44:27+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Datasets(BaseModel):
    names: Optional[List[str]] = None


class Models(BaseModel):
    names: Optional[List[str]] = None


class Job(BaseModel):
    id: Optional[float] = Field(None, example=1)


class Metric(BaseModel):
    values: Optional[float] = Field(None, example=0.8)


class Progress(BaseModel):
    progress: Optional[float] = Field(None, example=0.82)


class JobConfig(BaseModel):
    id: Optional[int] = Field(None, example=10)
    dataset: str = Field(..., example='cifar')
    model: str = Field(..., example='resnet50')


class Error(BaseModel):
    code: str
    message: str


class DatasetUploadPostRequest(BaseModel):
    file: bytes


class ModelUploadPostRequest(BaseModel):
    file: bytes


class Result(BaseModel):
    metrics: Optional[List[Metric]] = None
