from datetime import datetime
from typing import Optional

from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import Paragraph, Spacer

from report.pdf_sections.pdf_section import PDFSection
from report.pdf_sections.utils import ModelInfo


class Title(PDFSection):
    """This class creates the title of the PDF"""

    def __init__(
            self,
            corpus_width: Optional[float] = None,
            title_style: Optional[ParagraphStyle] = None,
            subtitle_style: Optional[ParagraphStyle] = None,
            description_style: Optional[ParagraphStyle] = None,
            date_format: str = '%B %d, %Y',
            pdf_title_style: Optional[ParagraphStyle] = None,
    ):
        super().__init__(
            corpus_width=corpus_width,
            title_style=title_style,
            subtitle_style=subtitle_style,
            description_style=description_style
        )
        self.date_format = date_format
        self.pdf_title_style = pdf_title_style

    def build(
            self,
            data: ModelInfo | dict,
            description: Optional[str] = None
    ) -> list:
        if isinstance(data, dict):
            data: ModelInfo = ModelInfo.model_validate(data)

        model_name: str = data.name if data.name else "target model"
        elements = []

        # Title
        elements.append(
            Paragraph(
                text="Model Trustworthiness Report",
                style=self.pdf_title_style
            )
        )

        # Subtitle with model name
        elements.append(
            Paragraph(
                text=f"Model: {model_name}",
                style=self.description_style
            )
        )
        elements.append(Spacer(1, 30))

        # Report metadata
        elements.append(
            Paragraph(
                text=f"""
                <font size=10>
                <b>Report Date:</b> {datetime.now().strftime(self.date_format)}<br/>
                <b>Generated By:</b> Leonardo S.p.A. <br/>
                </font>
                """,
                style=self.description_style
            )
        )
        elements.append(Spacer(1, 50))

        return elements
