evaluation:
  statistics:
    - name: 'countsamples'
    - name: 'accuracy'
      average: 'macro'
    - name: 'precision'
      average: 'macro'
    - name: 'robustness'
    - name: 'misclassification'

options:
  load_results: false                 # loading any existing results.
  overwrite: true                     # overwriting the results if a benchmarking is performed
  num_images_to_save: -1
  save_perturbation: false
  gpu: true
  output_path: "./benchmark_out" # Path to the output folder
  output_format: "report" # report or test

datasets:
  - name: "imagenet" # Name of the dataset
    num_classes: 90
    subset: 50
    batch: 2
    type_dataset: 2
    num_workers: 2
    source_path: "animals/data" # "../data/military/dataset/test/" # Path to the dataset
    transform_config:
      size: 256
      crop: 224
      transform_id: "imagenet_like_crop"
      mean: [0.5074, 0.5308, 0.5306]
      std: [0.2639, 0.2518, 0.2521]

models:
  - name: 'resnetv2_50d_evos.ah_in1k'
    type: 'timm'
    pretrained: True
    num_classes: 1000
    task: "classification"

attacks:
  - name: 'fgsm'
    id: 'vanilla-fgsm'
  - name: 'banditprior'
    max_iters: 30
    losses: ["misclassification"]

