evaluation:
  subset: 500
  batch: 20
  type_dataset: 1
  num_workers: 2
  statistics: [ "all" ]
  max_iters: 120

options:
  load_results: false                 # loading any existing results.
  overwrite: true                     # overwriting the results if a benchmarking is performed
  num_images_to_save: 10
  save_perturbation: true
  gpu: true
  model: 'resnet101.a1_in1k'
  attacks: [ 'fgsm','pgd', 'dag', 'du', 'patchfgsm']

  losses: [ "misclassification",
            "totalvariation",
            "similarity",
            "bound" ]

  list_models: [ 'resnet101.a1_in1k',
                 'resnet101.a1h_in1k',
                 'resnet101.a2_in1k',
                 'resnet101.gluon_in1k',
                 'resnet101.tv_in1k',
                 'resnet101c.gluon_in1k',
                 'resnet101d.gluon_in1k',
                 'resnet152.a1_in1k',
                 'resnet152.a1h_in1k',
                 'resnet152.a2_in1k',
                 'resnet152.gluon_in1k',
                 'resnet152.tv_in1k',
                 'resnet152c.gluon_in1k',
                 'resnet152d.gluon_in1k',
                 'resnet152s.gluon_in1k' ]                    # List of models to evaluate.


path:
  dataset: "../../data/imagenet-1k/val_images" # Path to the dataset
  out: './data/imagenet1k-2012-vext/'
