evaluation:
  statistics:
    - name: 'countsamples'
    - name: 'accuracy'
      average: 'macro'
    - name: 'precision'
      average: 'macro'
    - name: 'robustness'
    - name: 'misclassification'

options:
  load_results: false            # Load any existing results
  overwrite: true                # Overwrite results if benchmarking is performed
  num_images_to_save: -1
  save_perturbation: false
  gpu: true
  output_path: "./benchmark_out" # Path to the output folder
  output_format: "report"        # "report" or "test"

datasets:
  - name: "animals"             # Dataset name
    num_classes: 90
    subset: 10
    batch: 32
    type_dataset: 2
    num_workers: 2
    source_path: "/home/cristiano-carta/Desktop/datasets/animals/data"
    transform_config:
      size: 256
      crop: 224
      transform_id: "imagenet_like_crop"
      mean: [0.5074, 0.5308, 0.5306]
      std: [0.2639, 0.2518, 0.2521]

models:
  - name: 'convnext_base.clip_laion2b_augreg_ft_in12k_in1k'
    type: 'timm'
    pretrained: true
    num_classes: 1000
    task: "classification"
  - name: 'resnet50'
    type: 'timm'
    pretrained: true
    num_classes: 1000
    task: "classification"

attacks:
  - name: 'fgsm'
    max_iters: 50
  - name: 'pgd'
    max_iters: 50
  - name: 'banditprior'
    max_iters: 100
