evaluation:
  statistics:
    - name: 'countsamples'
    - name: 'accuracy'
      average: 'macro'
    - name: 'precision'
      average: 'macro'
    - name: 'robustness'
    - name: 'misclassification'

options:
  load_results: false                 # loading any existing results.
  overwrite: true                     # overwriting the results if a benchmarking is performed
  num_images_to_save: -1
  save_perturbation: false
  gpu: true
  output_path: "./benchmark_out" # Path to the output folder
  output_format: "report" # report or test
  mode : "single_node_serial"
  num_workers : 1
  num_gpus_per_worker : 1
  executor_type : "ray"


datasets:
  - name: "clean-aircraft-crop"             # Dataset name
    num_classes: 36
    subset: 60
    batch: 20
    type_dataset: 2
    num_workers: 2
    source_path: "/home/bru/Documents/codes/data/aircraft-dataset/clean-aircraft-crop"
    transform_config:
      transform_id: "normalize_only"
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

models:

  - model_path: "/home/bru/Documents/codes/nn_trust_apps/attack_server/models_repo/timm@convnextv2_base.fcmae_ft_in1k"

  - model_path: "/home/bru/Documents/codes/nn_trust_apps/attack_server/models_repo/timm@vit_base_patch16_224.augreg2_in21k_ft_in1k"

attacks:
  - name: 'fgsm'
    max_iters: 20
  - name: 'banditprior'
    max_iters: 50
  - name: 'dag'
    max_iters: 50


